### ISSUE TITLE
Authentication fail with vDIM configured

### ISSUE THREAD

**Issue by jlg-io** [vmware/ansible-for-nsxt#276]
With vIDM configued on NSX-T, we need to supply an Authorization header with a based64-encoded string.

With the given example in the README:

```yaml
- hosts: localhost
  tasks:
    - name: Update Tier0
      nsxt_policy_tier0:
        hostname: "default"
        request_headers:
          Authorization: 'Remote anNtaXRoQGV4YW1wbGUuY29tOlNrMkxrUE0h'
        validate_certs: False
        display_name: test-tier0-1
        state: present
```
It seems there is no scenario implemented in policy_communicator.py to support this:

```python
        if mgr_username is not None:
            if mgr_password is None:
                raise InvalidInstanceRequest("mgr_password ")
            key = tuple([mgr_hostname, mgr_username, mgr_password])
        elif nsx_cert_path is not None:
            if not nsx_cert_path.endswith('.p12') and nsx_key_path is None:
                raise InvalidInstanceRequest("nsx_key_path")
            key = tuple([mgr_hostname, nsx_cert_path, nsx_key_path])
        elif get_certificate_file_path('NSX_MANAGER_CERT_PATH') is not None:
            nsx_cert_path = get_certificate_file_path('NSX_MANAGER_CERT_PATH')
            key = tuple([mgr_hostname, nsx_cert_path])
        else:
            raise InvalidInstanceRequest("(mgr_username, mgr_password) or"
                                         "(nsx_cert_path, nsx_key_path), or "
                                         "environment variable "
                                         "'NSX_MANAGER_CERT_PATH'")
```
So we keep getting the error because nor mgr_username/password or nesx_cert_path/key are specified.

Am I missing something here ?
