### ISSUE TITLE
vIDM NSX-t 2.5

### ISSUE THREAD

**Issue by bannov** [vmware/ansible-for-nsxt#303]
Hello all,

is it still not possible to authenticate through vIDM in NSX-t 2.5 with "non policy-api"?
I have found the issue #276  and its not clear, will vIDM Authentication provided for "non policy-api"?

I am getting an Error 
`  "msg": "Unsupported parameters for (nsxt_transport_nodes) module: request_headers ...`

**Comment by madhukark** [comment]
Internal bug created.

**Comment by madhukark** [comment]
@bannov ,

could you share the full ansible module you are using and the complete error message please.

**Comment by bannov** [comment]
Hello @madhukark,

here is ansible output with -vvv key. for module   nsxt_logical_switches from master commit  6273ddc

```
---
- name: "Segment"
  nsxt_logical_switches:
    hostname:  "{{ nsxt_mgr }}"
    request_headers: "{{ request_headers }}"
    validate_certs: "{{ validate_certs }}"
    display_name: "{{ segment.display_name }}"
    description: "{{ segment.description }}"
    replication_mode: "{{ segment.replication_mode }}"
    admin_state: "{{ segment.admin_state }}"
    transport_zone_name: "{{ segment.transport_zone_name }}"
    vlan: "{{ segment.vlan | default(omit) }}" 
    tags: "{{ segment.tags }}"
    state: "{{ state }}"
...
```

```
fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "admin_state": "UP",
            "description": "Netz/Layer2",
            "display_name": "segment",
            "hostname": "nsxmgr.xx",
            "replication_mode": "MTEP",
            "request_headers": {
                "Authorization": "Remote base64xxxxx"
            },
            "state": "present",
            "tags": [
                {
                    "scope": "test",
                    "tag": "test"
                }
            ],
            "transport_zone_name": "tz-overlay",
            "validate_certs": true
        }
    },
    "msg": "Unsupported parameters for (nsxt_logical_switches) module: request_headers Supported parameters include: address_bindings, admin_state, description, display_name, extra_configs, hostname, hybrid, ip_pool_name, lswitch_id, mac_pool_id, mac_pool_name, password, port, replication_mode, span, state, switch_type, switching_profiles, tags, transport_zone_name, uplink_teaming_policy_name, username, validate_certs, vlan, vlan_trunk_spec, vni"
}
´´´
```


I have tested the same for  nsxt_ip_blocks and nsxt_ip_pools. getting the same error. It seems that modules dont recognisen request_headers field.

`fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (nsxt_ip_blocks) module: request_headers Supported parameters include: cidr, description, display_name, hostname, password, port, state, tags, username, validate_certs"}`


`fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (nsxt_ip_pools) module: request_headers Supported parameters include: description, display_name, hostname, ip_release_delay, password, port, state, subnets, tags, username, validate_certs"}`
