### ISSUE TITLE
Fail to update edge nodes with nsxt_transport_nodes

### ISSUE THREAD

**Issue by roundtripdelay** [vmware/ansible-for-nsxt#338]
Hi. I am able to successfully deploy edge VMs with the version 3.0 modules using nsxt_transport_nodes against NSX-T 3.1. However, an error occurs and the task fails when the playbook is re-run:

Error[(9533, {'httpStatus': 'BAD_REQUEST', 'error_code': 9533, 'module_name': 'NsxSwitching service', 'error_message': 'Cannot modify Transport zone endpoints at HostSwitch as well as at TransportNode level.'})]."}

I'm not specifying the transport zone endpoints at the TransportNode level (as far as I can tell). Is this maybe an issue with using these modules with NSX-T 3.1? Thanks for the help.

Below is the host_vars for the edge VM:

```
nsx_edge_nodes:
  - display_name: nsxen01
    description: "NSX Edge Node 1"
    host_switch_name: nvds-prod
    pnics:
      - device_name: fp-eth0
        uplink_name: "{{ nsx_teaming_policy_uplink1 }}"
      - device_name: fp-eth1
        uplink_name: "{{ nsx_teaming_policy_uplink2 }}"
    transport_zone_endpoints:
      - transport_zone_name: nsx-overlay-prod
      - transport_zone_name: nsx-vlan-prod
    node_deployment_info:
      deployment_type: VIRTUAL_MACHINE
      display_name: nsxen01
      resource_type: EdgeNode
      deployment_config:
        form_factor: MEDIUM
        node_user_settings:
          cli_password: "{{ vault_nsx_admin_password }}"
          cli_username: admin
          root_password: "{{ vault_nsx_admin_password }}"
        vm_deployment_config:
          allow_ssh_root_login: true
          compute: "{{ core_vc[0]['cluster'] }}"
          data_networks:
            - ext1
            - ext2
          default_gateway_addresses:
            - "{{ nsx_gateway }}"
          dns_servers: "{{ dns }}"
          enable_ssh: true
          hostname: atl-core-nsxen01
          management_network: "{{ nsx_mgmt_portgroup }}"
          management_port_subnets:
            - ip_addresses:
              - 10.2.1.17
              prefix_length: 26
          ntp_servers: "{{ ntp_servers }}"
          placement_type: VsphereDeploymentConfig
          storage: "{{ core_vc[0]['datastore'] }}"
          vc_name: "{{ core_vc[0]['display_name'] }}"
          vc_username: "{{ core_vc[0]['username'] }}"
          vc_password: "{{ core_vc[0]['password'] }}"
```

Below is the play:

```
    - name: Create Edge VM transport nodes
      nsxt_transport_nodes:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{ item.display_name }}"
        host_switch_spec:
          resource_type: "StandardHostSwitchSpec"
          host_switches:
            - host_switch_profiles:
              - name: "{{ nsx_hostswitch_edge }}"
                type: UplinkHostSwitchProfile
              host_switch_mode: STANDARD
              host_switch_name: "{{ item.host_switch_name }}"
              ip_assignment_spec:
                resource_type: StaticIpPoolSpec
                ip_pool_name: "{{ nsx_vtep_ip_pool }}"
              pnics: "{{ item.pnics }}"
              transport_zone_endpoints: "{{ item.transport_zone_endpoints }}"
        node_deployment_info: "{{ item.node_deployment_info }}"
        state: "present"
      delegate_to: localhost
      loop: "{{ nsx_edge_nodes }}"
      tags: current
```
