### ISSUE TITLE
nsxt_virtual_ip is not idempotent

### ISSUE THREAD

**Issue by lvlie** [vmware/ansible-for-nsxt#352]
When using the latest version of the `nsxt_virtual_ip` module against an NSX Manager 3.1.1 instance, the task is not idempotent (always returns changed):

```
TASK [deploy : Register cluster VIP address] *********************************************************************************************
changed: [nsx-manager] => {"changed": true, "message": "Virtual IP address is set with ip address: 192.168.0.10 ", "result": {"ip_address": "192.168.0.10"}}
```

I fixed this locally with:
```
- name: Get cluster VIP address
  nsxt_virtual_ip_facts:
    hostname: "{{ nsxmanager }}"
    username: "{{ nsxuser }}"
    password: "{{ nsxpass }}"
  register: vip
```
And a when statement on the `nsxt_virtual_ip`:
```
  when: vip.ip_address != nsx_manager_ip or vip_facts.ip_address is not defined
```

But this should really be fixed in the module itself.
