### ISSUE TITLE
vmware.ansible_for_nsxt.nsxt_policy_segment broke after PR #370

### ISSUE THREAD

**Issue by lvlie** [vmware/ansible-for-nsxt#371]
My automated pipeline seized to work all of a sudden, while local runs still succeeded. After updating my local collection for nsxt (only change being #370) it stopped working locally as well. 

The error:
```
TASK [nsx-network : Create NSX-T Edge VLAN Segments] ***********************************************************************************************************************************************************************************
failed: [nestedlab] (item=nestedlab-vl100) => {"ansible_loop_var": "segment", "changed": false, "msg": "Received 400 from NSX Manager. Please try again. Invalid transport zone path /infra/sites/default/enforcement-points/default/transport-zones/nested-vlan-tz specified.", "segment": {"ip": "10.10.10.10/29", "name": "nestedlab-vl100", "replication_mode": "MTEP", "transport_zone": "nested-vlan-tz", "uplink_profile": "nested-edge-uplink1", "vlan": 100}}
```

There are some changes related to paths in the mentioned PR, and it seems one of them broke (at least) this module.

Maybe it makes sense to properly version this collection in the meantime, so there is an easy way to revert to using an older version if something breaks.

**Comment by lvlie** [comment]
FYI, this is the code I am using:
```yaml
- name: Create NSX-T Edge VLAN Segments
  vmware.ansible_for_nsxt.nsxt_policy_segment:
    hostname: "{{ nsx.manager }}"
    username: "{{ nsx.user }}"
    password: "{{ nsx.pass }}"
    validate_certs: False
    display_name: "{{ segment.name }}"
    description: "{{ segment.name }}"
    admin_state: "UP"
    replication_mode: "{{ segment.replication_mode }}"
    transport_zone_display_name: "{{ segment.transport_zone }}"
    advanced_config:
      uplink_teaming_policy_name: "{{ segment.uplink_profile }}"
    vlan_ids:
      - "{{ segment.vlan }}"
    subnets:
      - gateway_address: "{{ segment.ip }}"
    state: "present"
  loop: "{{ nsx.edge.segments }}"
  loop_control:
    loop_var: segment
    label: "{{ segment.name }}"

```

**Comment by lvlie** [comment]
For anyone waiting for this to be noticed by VMware and not needing any new commits for other bugs; you can specify this in your collection requirements to use the last working version for creating segments:
```yaml
  - name: https://github.com/vmware/ansible-for-nsxt.git
    type: git
    version: cfc58b6b2898253f064febe2c3243dc02efa9c63
```
