### ISSUE TITLE
nsxt_policy_segment subnet key fail when no subnet defined

### ISSUE THREAD

**Issue by chaddchaffee** [vmware/ansible-for-nsxt#372]
`subnet` is a listed as an optional parameter, however, seems that `def _updateSubnetsAsPerIpvType` fails with key error when no subnet parameter is listed.

Use case to reproduce, using NSXT v3.1:
```
---
- name: Uplink Segments for VRF Tier0
  nsxt_policy_segment:
    state: present
    nsxt_manager: "{{ manager_ip }}"
    nsxt_manager_username: "{{ nsxt_username }}"
    nsxt_manager_password: "{{ nsxt_password }}"
    segment_name: "Segment_name"
    nsx_vlan_transport_zone: "transport_zone_1"
    vlan_ids:
    - 10
    - 20
    
```

Commenting out lines 1130-1150 in the module fixed the issue, whose changes are tied to PR #345 . I believe it's expecting a parameter that is not actually required, but causing fail when it's not defined.
