### ISSUE TITLE
Credentials via environment variables

### ISSUE THREAD

**Issue by slauger** [vmware/ansible-for-nsxt#381]
In other available VMware automation tools (e.g. ansible vmware collection, terraform-provider-nsxt) it is always possible to set the credentials via environment variables.

It seems that this is not the case for ansible-for-nsxt.

It would be great if ansible-for-nsxt would support the same environment variables as [terraform-provider-nsxt](https://github.com/vmware/terraform-provider-nsxt)

- `NSXT_ALLOW_UNVERIFIED_SSL`
- `NSXT_MANAGER_HOST`
- `NSXT_PASSWORD`
- `NSXT_USERNAME`

That would massively reduce the size of the code to be written.

Currently this is necessary to support the environment variables:

```
- name: setup nsxt virtual machine tags
  gather_facts: false
  hosts:
    - all
  tasks:
    - name: add cluster-id tag to nsx-t
      vmware.ansible_for_nsxt.nsxt_vm_tags:
        hostname: "{{ lookup('env', 'NSXT_MANAGER_HOST') }}"
        username: "{{ lookup('env', 'NSXT_USERNAME') }}"
        password: "{{ lookup('env', 'NSXT_PASSWORD') }}"
        validate_certs: false
        virtual_machine_display_name: "{{ inventory_hostname }}"
        remove_other_tags: False
        add_tags:
          - scope: foo
            tag: "bar"
      delegate_to: localhost
```
