### ISSUE TITLE
Ability to delete nsxt_policy_group object

### ISSUE THREAD

**Issue by Xat59** [vmware/ansible-for-nsxt#405]
Hi guys,

I could be very useful to be able to delete `nsxt_policy_group` objects through the ansible module, such as :

```yaml
- name: Create NSXT Policy Group IPAddressExpression
  vmware.ansible_for_nsxt.nsxt_policy_group:
    hostname: "{{ nsxt_hostname }}"
    username: "{{ nsxt_username }}"
    password: "{{ nsxt_password }}"
    validate_certs: false
    display_name: "{{ object.name }}"
    id: "{{ object.name }}"
    domain_id: "{{ object.domain }}"
    description: "{{ object.description }}"
    state: absent
    expression:
    - resource_type: IPAddressExpression
      ip_addresses:
      - "{{ object.addr | ansible.netcommon.ipaddr('network/prefix') }}"
```

Regards.
