### ISSUE TITLE
Ability to delete nsxt_policy_security_policy objects

### ISSUE THREAD

**Issue by Xat59** [vmware/ansible-for-nsxt#406]
Hi guys,

such as the `nsxt_policy_group` objects (https://github.com/vmware/ansible-for-nsxt/issues/405) , it could be very useful to be able to delete `nsxt_policy_security_policy` objects through the ansible module, such as :

```yaml
- name: Delete NSXT Security Policy
  vmware.ansible_for_nsxt.nsxt_policy_security_policy:
    hostname: "{{ nsxt_hostname }}"
    username: "{{ nsxt_username }}"
    password: "{{ nsxt_password }}"
    validate_certs: false
    display_name: "defaultsection"
    domain_id: "default"
    category: "Application"
    state: absent
```

Regards.
