### ISSUE TITLE
nsxt_upgrade_upload_mub with "file" does not work because of size limit

### ISSUE THREAD

**Issue by lvlie** [vmware/ansible-for-nsxt#416]
### Describe the bug

When trying to upload the mub file from the ansible controller, using the following task:

```yaml
- name: Upload upgrade file to NSX-T manager coordinator node from file
  vmware.ansible_for_nsxt.nsxt_upgrade_upload_mub:
    hostname: "{{ coordinator }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: False
    file: "{{ nsx_upgrade_mub_file }}"
```

The task will fail with the following error message:
```
fatal: [cdt_wpr_red]: FAILED! => {
    "changed": true,
    "invocation": {
        "module_args": {
            "file": "***/VMware-NSX-upgrade-bundle-3.1.3.5.0.19068434.mub",
            "hostname": "***",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "timeout": null,
            "url": null,
            "username": "***",
            "validate_certs": false
        }
    },
    "msg": "Error: string longer than 2147483647 bytes"
```

Maybe the upgrade bundle was smaller than 2Gb at some point, but now its not anymore. Manually uploading the mub works fine, but getting it from a webserver requires it to run on http only (no TLS) because it seems to fail on our internal CA certs (even when they are added to the normal truststore using the certificates task).

### Reproduction steps

```bash
1. Install python (latest)
2. Install ansible (latest)
3. Run the nsxt_upgrade_upload_mub with the file parameter
```

### Expected behavior

mub file is uploaded and ready to be used
