### ISSUE TITLE
Datacenter, cluster and network names when deploying an Edge

### ISSUE THREAD

**Issue by laidbackware** [vmware/ansible-for-nsxt#66]
Currently when deploying an Edge the module requires the vCenter object names to be added, not the nice names. Such as 'domain-c7' for the vSphere cluster. This means that you can't rely on a static answers file if re-using, as the object identifiers can change. Please add the capability for the module to convert nice name to the vCenter object reference.

**Comment by rhernaus** [comment]
In the meantime you can use [vcenter_query.py](https://github.com/vmware/ansible-module-chaperone/blob/master/vcenter_query.py)

```
- name: Get portgroup moid
  vcenter_query:
    hostname: "{{ cm_ip }}"
    username: "{{ cm_username }}"
    password: "{{ cm_password }}"
    validate_certs: False
    vcenter_object_name: "{{ cm_portgroup }}"
    vcenter_vim_type: "dvs-port"
  register: cm_portgroup_moid

- name: Get cluster moid
  vcenter_query:
    hostname: "{{ cm_ip }}"
    username: "{{ cm_username }}"
    password: "{{ cm_password }}"
    validate_certs: False
    vcenter_object_name: "{{ cm_cluster }}"
    vcenter_vim_type: "cluster"
  register: cm_cluster_moid

- name: Get datastore moid
  vcenter_query:
    hostname: "{{ cm_ip }}"
    username: "{{ cm_username }}"
    password: "{{ cm_password }}"
    validate_certs: False
    vcenter_object_name: "{{ cm_datastore }}"
    vcenter_vim_type: "datastore"
  register: cm_datastore_moid
```
